project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: "Presentaci√≥n"
      - href: desarrollo.qmd
        text: "Desarrollo"
      - href: estimacion.qmd
        text: "Estimaciones"
  search: false
  
execute:
  freeze: true

format:
  html:
    theme:
      - default
    css: style.css
    toc: true



